name: ocean_hack
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.7+5
  dio: ^5.2.1
  mongo_dart: ^0.9.1
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  logger: ^1.4.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  table_calendar: ^3.0.8
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^23.1.36
  flutter_custom_clippers: ^2.1.0
  flutter_animated_button: ^2.0.3
  percent_indicator: ^4.2.3
  flutter_typeahead: ^4.8.0
  easy_date_timeline: ^0.1.1
  flutter_staggered_animations: ^1.1.1
  youtube_player_iframe: ^4.0.4
  form_builder_image_picker: ^4.0.0
  bloc: ^8.1.2
  dotted_border: ^2.1.0
  introduction_screen: ^3.1.12
  google_nav_bar: ^5.0.6
  flutter_rating_bar: ^4.0.1
  flip_card: ^0.7.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  syncfusion_flutter_pdfviewer: ^23.1.39
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/ai_model/
    # - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
